version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mediconnect-db
    environment:
      POSTGRES_USER: mediconnect_user
      POSTGRES_PASSWORD: mediconnect_password
      POSTGRES_DB: mediconnect_db
    ports:
      - "5433:5432"
    volumes:
      # Mount the schema file to initialize the database
      - ./mediconnect_id_schema.sql:/docker-entrypoint-initdb.d/init.sql        
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: mediconnect-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: mediconnect-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672" # Management UI
    restart: unless-stopped

  backend:
    image: ghalitsar/backend-app:v2
    container_name: mediconnect-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
      - rabbitmq
    env_file:
      - .env
    environment:
      - REDIS_URL=redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    restart: unless-stopped
