name: Deploy Backend

on:
  push:
    branches:
      - master

env:
  BACKEND_IMAGE_NAME: ghalitsar/backend-app:v2

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.BACKEND_IMAGE_NAME }}

  deploy:
    needs: build-and-push-backend
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "Generating .env file..."
          cat <<EOF > .env
          APP_ENV=production
          SERVER_PORT=8080
          AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          DB_URL=${{ secrets.DB_URL }}
          REDIS_URL=redis:6379
          RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
          EOF

      - name: Deploying Healthcare App
        run: |
          echo "Pulling latest image and deploying..."
          
          # Hapus container lama (dari metode SSH manual) yang bikin bentrok nama
          docker rm -f mediconnect-backend mediconnect-db mediconnect-redis mediconnect-rabbitmq || true
          
          docker pull ${{ env.BACKEND_IMAGE_NAME }}
          
          docker compose down
          docker compose up -d --force-recreate
          
          echo "Cleaning up old images..."
          docker image prune -f